"""
WhatsApp Flows: structured forms that render natively inside a WhatsApp chat.

A Flow is authored once as Flow JSON (a small declarative screen/component
spec - Meta's own format, not ours), pushed to Meta via the Graph API, and
from then on referenced by its Meta-assigned flow_id whenever a business
wants to send it. This table is the business's own library of flows: what
they authored, what Meta currently thinks its status is, and enough to
re-send or re-publish it without re-reading Meta first.

Scoped deliberately to navigate-only flows for this pass - a flow whose
screens branch on data the flow itself already has, not one that calls back
to a data_exchange endpoint mid-flow for options computed live (available
slots, search results). Meta's own docs are explicit that navigate flows
need no endpoint at all; a data_exchange flow needs a business to run an
encrypted request/response endpoint (RSA keypair registered with Meta, every
payload AES-encrypted), which is real infrastructure worth building only
once a template actually needs live data mid-form rather than up front.
"""

import enum
import uuid
from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, Index, String, UniqueConstraint
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects.postgresql import UUID as PgUUID
from sqlalchemy.orm import Mapped, mapped_column

from shared.db.base import Base, TimestampMixin, UUIDMixin
from shared.db.types import EnumType


class FlowStatus(str, enum.Enum):
    # Mirrors Meta's own flow status vocabulary, so the value stored here
    # never needs translating when read back from a Graph response.
    draft = "DRAFT"
    published = "PUBLISHED"
    deprecated = "DEPRECATED"


class WhatsAppFlow(UUIDMixin, TimestampMixin, Base):
    __tablename__ = "whatsapp_flows"

    business_id: Mapped[uuid.UUID] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("businesses.id", ondelete="CASCADE"),
        nullable=False,
    )

    # Meta's own id for this flow - what every later Graph call and every
    # outbound flow message addresses it by.
    meta_flow_id: Mapped[str] = mapped_column(String(64), nullable=False)

    name: Mapped[str] = mapped_column(String(255), nullable=False)
    # Meta's fixed vocabulary (SIGN_UP, APPOINTMENT_BOOKING, LEAD_GENERATION,
    # CONTACT_US, CUSTOMER_SUPPORT, SURVEY, OTHER, ...) - kept as their raw
    # strings, same reasoning as VoiceProvisioning.compliance_raw_status.
    categories: Mapped[list] = mapped_column(JSONB, nullable=False, default=list)

    status: Mapped[FlowStatus] = mapped_column(
        EnumType(FlowStatus, 20), nullable=False, default=FlowStatus.draft
    )

    # The Flow JSON exactly as uploaded - kept so the business can see and
    # re-send what they authored without a Graph round trip, and so a
    # validation failure can be shown against the version that produced it.
    flow_json: Mapped[dict] = mapped_column(JSONB, nullable=False)
    # [{"error_type": ..., "message": ..., "line_start": ..., ...}, ...] from
    # Meta's own validator - empty once the flow is clean.
    validation_errors: Mapped[list] = mapped_column(JSONB, nullable=False, default=list)

    __table_args__ = (
        UniqueConstraint("business_id", "meta_flow_id", name="uq_flow_meta_id"),
        Index("idx_flows_business", "business_id"),
    )


class FlowSendLog(UUIDMixin, TimestampMixin, Base):
    """
    One flow message sent to one customer - just enough to match a later
    completion (an inbound nfm_reply) back to the flow it came from, since
    the webhook only carries the flow_token, not the flow's own id or name.
    """

    __tablename__ = "whatsapp_flow_sends"

    business_id: Mapped[uuid.UUID] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("businesses.id", ondelete="CASCADE"),
        nullable=False,
    )
    flow_id: Mapped[uuid.UUID] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("whatsapp_flows.id", ondelete="CASCADE"),
        nullable=False,
    )
    customer_id: Mapped[uuid.UUID] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("customers.id", ondelete="CASCADE"),
        nullable=False,
    )
    # Unique per send, generated by us - the one thing WhatsApp hands back
    # unchanged on completion, so it is the join key to this row.
    flow_token: Mapped[str] = mapped_column(String(255), nullable=False)
    # Set when the matching nfm_reply arrives - null means still open or
    # abandoned, the only two states WhatsApp gives us no way to tell apart.
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    __table_args__ = (
        UniqueConstraint("business_id", "flow_token", name="uq_flow_token"),
        Index("idx_flow_sends_token", "business_id", "flow_token"),
    )
