"""add voice_provisioning table

Revision ID: 7f7b593f913e
Revises: 269dabf947ee
Create Date: 2026-08-24 20:17:00.502835
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy as sa

revision: str = '7f7b593f913e'
down_revision: str | None = '269dabf947ee'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice_provisioning',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('subaccount_auth_id', sa.String(length=64), nullable=False),
    sa.Column('subaccount_auth_token', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('end_user_id', sa.String(length=64), nullable=True),
    sa.Column('compliance_requirement_id', sa.String(length=64), nullable=True),
    sa.Column('compliance_application_id', sa.String(length=64), nullable=True),
    sa.Column('compliance_raw_status', sa.String(length=50), nullable=True),
    sa.Column('compliance_rejection_reason', sa.Text(), nullable=True),
    sa.Column('documents', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id')
    )
    op.create_index('idx_voice_provisioning_business', 'voice_provisioning', ['business_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_voice_provisioning_business', table_name='voice_provisioning')
    op.drop_table('voice_provisioning')
    # ### end Alembic commands ###
