"""message templates

Revision ID: d16f2934bc4a
Revises: ccf0d8867fb9
Create Date: 2026-08-23 16:06:56.327161
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy as sa

revision: str = 'd16f2934bc4a'
down_revision: str | None = 'ccf0d8867fb9'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_templates',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=True),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('edit_count', sa.Integer(), nullable=False),
    sa.Column('last_edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['connection_id'], ['channel_connections.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'name', 'language', name='uq_template_name_language')
    )
    op.create_index('idx_templates_business_status', 'message_templates', ['business_id', 'status'], unique=False)
    op.create_index('idx_templates_external', 'message_templates', ['external_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_templates_external', table_name='message_templates')
    op.drop_index('idx_templates_business_status', table_name='message_templates')
    op.drop_table('message_templates')
    # ### end Alembic commands ###
